# Generated by Django 5.2.3 on 2025-11-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0004_expertdelta_expertlearningstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertlog',
            name='action',
            field=models.CharField(choices=[('annotation_validated', 'Annotation validée'), ('annotation_rejected', 'Annotation rejetée'), ('annotation_modified', 'Annotation modifiée'), ('annotation_deleted', 'Annotation supprimée'), ('annotation_created', 'Annotation créée'), ('validation_undone', 'Validation annulée'), ('document_reviewed', 'Document révisé'), ('sentence_reviewed', 'Phrase révisée'), ('annotation_type_created', "Type d'annotation créé"), ('annotation_type_deleted', "Type d'annotation supprimé")], max_length=60),
        ),
    ]
