# Generated by Django 5.2.3 on 2025-11-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0005_alter_expertlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertlog',
            name='action',
            field=models.CharField(choices=[('annotation_validated', 'Annotation validée'), ('annotation_rejected', 'Annotation rejetée'), ('annotation_modified', 'Annotation modifiée'), ('annotation_deleted', 'Annotation supprimée'), ('annotation_created', 'Annotation créée'), ('validation_undone', 'Validation annulée'), ('document_reviewed', 'Document révisé'), ('sentence_reviewed', 'Phrase révisée'), ('annotation_type_created', "Type d'annotation créé"), ('annotation_type_deleted', "Type d'annotation supprimé"), ('relationship_validated', 'Relation validée'), ('relationship_rejected', 'Relation rejetée'), ('relationship_modified', 'Relation modifiée')], max_length=60),
        ),
    ]
