# Generated by Django 5.2.3 on 2025-11-09 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0006_alter_expertlog_action'),
        ('rawdocs', '0028_annotationrelationship_is_validated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_type', models.CharField(choices=[('question', 'Question'), ('answer', 'Réponse'), ('correction', 'Correction'), ('suggestion', 'Suggestion'), ('note', 'Note')], default='question', max_length=20)),
                ('content', models.TextField(help_text='Contenu du message')),
                ('json_path', models.CharField(blank=True, help_text='Chemin dans le JSON concerné (ex: annotations.entities.Product[0])', max_length=500)),
                ('json_data', models.JSONField(blank=True, default=dict, help_text='Extrait du JSON concerné par le message')),
                ('is_resolved', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags pour catégoriser le message (relations, entities, qa, etc.)')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='rawdocs.rawdocument')),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='expert.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['document', 'created_at'], name='expert_chat_documen_e753e7_idx'), models.Index(fields=['user', 'created_at'], name='expert_chat_user_id_0bb03c_idx'), models.Index(fields=['is_resolved'], name='expert_chat_is_reso_05e7f4_idx')],
            },
        ),
    ]
