# Generated by Django 5.2.3 on 2025-11-09 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0007_chatmessage'),
        ('rawdocs', '0028_annotationrelationship_is_validated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidatedQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Question posée')),
                ('question_normalized', models.TextField(help_text='Question normalisée (minuscules, sans accents, etc.)')),
                ('answer', models.TextField(help_text="Réponse validée par l'expert")),
                ('source_type', models.CharField(choices=[('json_entity', 'Entité JSON'), ('json_relation', 'Relation JSON'), ('json_field', 'Champ JSON'), ('expert_knowledge', 'Connaissance expert'), ('computed', 'Calculé/Déduit')], max_length=50)),
                ('json_path', models.CharField(blank=True, help_text='Chemin dans le JSON (ex: entities.Product[0].appearance)', max_length=500)),
                ('json_data', models.JSONField(blank=True, default=dict, help_text='Données JSON utilisées pour la réponse')),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correction_count', models.IntegerField(default=0, help_text='Nombre de fois que cette réponse a été corrigée')),
                ('previous_answers', models.JSONField(blank=True, default=list, help_text='Historique des réponses précédentes')),
                ('usage_count', models.IntegerField(default=0, help_text='Nombre de fois que cette Q&A a été utilisée')),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('confidence_score', models.FloatField(default=1.0, help_text='Score de confiance (0.0-1.0) basé sur les validations')),
                ('is_active', models.BooleanField(default=True)),
                ('is_global', models.BooleanField(default=False, help_text='Si True, applicable à tous les documents')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags pour faciliter la recherche (appearance, composition, etc.)')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validated_qa', to='rawdocs.rawdocument')),
                ('validated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_qa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-confidence_score', '-usage_count', '-validated_at'],
                'indexes': [models.Index(fields=['question_normalized'], name='expert_vali_questio_22892c_idx'), models.Index(fields=['document', 'is_active'], name='expert_vali_documen_413cb9_idx'), models.Index(fields=['is_global', 'is_active'], name='expert_vali_is_glob_68191e_idx'), models.Index(fields=['confidence_score', 'usage_count'], name='expert_vali_confide_2d1f26_idx')],
            },
        ),
    ]
