# Generated by Django 5.2.3 on 2025-10-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdocs', '0018_rawdocument_structured_html_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdocument',
            name='llama_suggested_types',
            field=models.JSONField(blank=True, help_text="Types d'annotation suggérés par Llama (cache)", null=True),
        ),
        migrations.AddField(
            model_name='rawdocument',
            name='llama_suggestions_at',
            field=models.DateTimeField(blank=True, help_text='Date des suggestions par Llama', null=True),
        ),
        migrations.AddField(
            model_name='rawdocument',
            name='mistral_analyzed',
            field=models.BooleanField(default=False, help_text="Document analysé par Mistral pour les types d'annotation"),
        ),
        migrations.AddField(
            model_name='rawdocument',
            name='mistral_analyzed_at',
            field=models.DateTimeField(blank=True, help_text="Date d'analyse par Mistral", null=True),
        ),
        migrations.AddField(
            model_name='rawdocument',
            name='mistral_document_domain',
            field=models.CharField(blank=True, help_text='Domaine/contexte détecté par Mistral', max_length=255),
        ),
        migrations.AddField(
            model_name='rawdocument',
            name='mistral_document_language',
            field=models.CharField(blank=True, help_text='Langue détectée par Mistral', max_length=10),
        ),
        migrations.AddField(
            model_name='rawdocument',
            name='mistral_suggested_types',
            field=models.JSONField(blank=True, help_text="Types d'annotation suggérés par Mistral (cache)", null=True),
        ),
    ]
