# Generated by Django 5.2.3 on 2025-10-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdocs', '0019_rawdocument_llama_suggested_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='planned_documents',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
