# Generated by Django 5.2.3 on 2025-10-05 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rawdocs', '0021_annotation_end_offset_annotation_end_xpath_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='end_offset',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='end_xpath',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='start_offset',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='start_xpath',
        ),
    ]
