# Generated by Django 5.2.3 on 2025-10-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdocs', '0021_annotation_end_offset_annotation_end_xpath_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdocument',
            name='mime_type',
            field=models.CharField(blank=True, help_text='Type MIME du fichier (PDF, Word, Excel, image, etc.)', max_length=100),
        ),
    ]
