# Generated by Django 5.2.3 on 2025-10-19 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rawdocs', '0022_remove_annotation_end_offset_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawdocument',
            name='llama_suggested_types',
        ),
        migrations.RemoveField(
            model_name='rawdocument',
            name='llama_suggestions_at',
        ),
        migrations.RemoveField(
            model_name='rawdocument',
            name='mistral_analyzed',
        ),
        migrations.RemoveField(
            model_name='rawdocument',
            name='mistral_analyzed_at',
        ),
        migrations.RemoveField(
            model_name='rawdocument',
            name='mistral_document_domain',
        ),
        migrations.RemoveField(
            model_name='rawdocument',
            name='mistral_document_language',
        ),
        migrations.RemoveField(
            model_name='rawdocument',
            name='mistral_suggested_types',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='planned_documents',
        ),
    ]
