# Generated by Django 5.2.3 on 2025-10-19 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rawdocs', '0022_rawdocument_mime_type'),
        ('rawdocs', '0023_remove_rawdocument_llama_suggested_types_and_more'),
    ]

    operations = [
    ]
