# Generated by Django 5.2.3 on 2025-10-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdocs', '0024_merge_20251019_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawdocument',
            name='mime_type',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='planned_documents',
            field=models.IntegerField(default=0),
        ),
    ]
