# Generated by Django 5.2.3 on 2025-10-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdocs', '0025_remove_rawdocument_mime_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='end_offset',
            field=models.IntegerField(blank=True, help_text='Character offset within end node', null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='end_xpath',
            field=models.TextField(blank=True, help_text='XPath to end node for structured annotations', null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='mode',
            field=models.CharField(choices=[('raw', 'Raw Text'), ('structured', 'Structured HTML')], default='raw', help_text='Annotation mode: raw text or structured HTML', max_length=20),
        ),
        migrations.AddField(
            model_name='annotation',
            name='start_offset',
            field=models.IntegerField(blank=True, help_text='Character offset within start node', null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='start_xpath',
            field=models.TextField(blank=True, help_text='XPath to start node for structured annotations', null=True),
        ),
    ]
